# Generated by Django 4.2 on 2023-04-27 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiktokCampaignObjectiveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'campaign_tiktok_objective_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TiktokCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=255, unique=True)),
                ('campaign_name', models.CharField(max_length=255, unique=True)),
                ('advertiser_id', models.CharField(max_length=255)),
                ('budget', models.FloatField(blank=True, default=0, max_length=100, null=True)),
                ('budget_mode', models.CharField(max_length=100)),
                ('operation_status', models.CharField(choices=[(1, 'Enabled'), (0, 'Disabled')], default=1)),
                ('objective', models.CharField(choices=[(1, 'App'), (2, 'Landing page')])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('objective_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiktok.tiktokcampaignobjectivetype')),
            ],
            options={
                'db_table': 'campaign_tiktok',
                'managed': True,
            },
        ),
    ]
