# Generated by Django 4.2 on 2023-04-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokcampaign',
            name='operation_status',
            field=models.CharField(choices=[('ENABLED', 'Enabled'), ('DISABLED', 'Disabled')], default='ENABLED'),
        ),
    ]
