# Generated by Django 4.2 on 2023-04-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0002_alter_tiktokcampaign_operation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokcampaign',
            name='operation_status',
            field=models.CharField(choices=[('ENABLE', 'Enabled'), ('DISABLE', 'Disabled')], default='ENABLE'),
        ),
    ]
