# Generated by Django 4.2 on 2023-04-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0003_alter_tiktokcampaign_operation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('REGULAR_CAMPAIGN', 'Regular campaign'), ('IOS14_CAMPAIGN', 'IOS14 campaign')], default='REGULAR_CAMPAIGN', max_length=100),
        ),
        migrations.AlterField(
            model_name='tiktokcampaign',
            name='operation_status',
            field=models.CharField(choices=[('ENABLE', 'Enable'), ('DISABLE', 'Disable')], default='ENABLE'),
        ),
    ]
