# Generated by Django 4.2 on 2023-04-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0004_tiktokcampaign_campaign_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('REGULAR_CAMPAIGN', 'Regular campaign'), ('IOS14_CAMPAIGN', 'IOS14 campaign')], max_length=100),
        ),
    ]
