# Generated by Django 4.2 on 2023-04-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0005_alter_tiktokcampaign_campaign_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiktokcampaign',
            name='campaign_type',
        ),
    ]
