# Generated by Django 4.2 on 2023-04-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0006_remove_tiktokcampaign_campaign_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokcampaign',
            name='budget_mode',
            field=models.CharField(choices=[('BUDGET_MODE_DAY', 'Budget mode day'), ('BUDGET_MODE_TOTAL', 'Budget mode total'), ('BUDGET_MODE_INFINITE', 'Budget mode infinite')], max_length=100),
        ),
    ]
