# Generated by Django 4.2 on 2023-04-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0007_alter_tiktokcampaign_budget_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokcampaign',
            name='objective_type',
            field=models.CharField(choices=[('WEB_CONVERSIONS', 'Web conversions'), ('REACH', 'Reach'), ('TRAFFIC', 'Traffic'), ('VIDEO_VIEWS', 'Video views'), ('PRODUCT_SALES', 'Product sales'), ('ENGAGEMENT', 'Engagement'), ('LEAD_GENERATION', 'Lead generation'), ('RF_REACH', 'RF Reach')], max_length=100),
        ),
        migrations.DeleteModel(
            name='TiktokCampaignObjectiveType',
        ),
    ]
