# Generated by Django 4.2 on 2023-04-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0008_alter_tiktokcampaign_objective_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiktokcampaign',
            name='objective',
        ),
    ]
